name: "Skip on comment"

on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/skip') && github.event.comment.user.login != 'ObsidianReviewBot'
    steps:
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: Skipped code scan
      - run: gh issue edit "$NUMBER" --add-assignee "$ASSIGNEE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          ASSIGNEE: joethei
